import type { Metadata } from "next";
import "./globals.css";
import { ConditionalLayout } from "@/components/ConditionalLayout";
import { AuthProvider } from "@/app/context/AuthContext";


export const metadata: Metadata = {
	title: "ATS by Team C",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="antialiased bg-slate-50">
				<AuthProvider>
					<ConditionalLayout>{children}</ConditionalLayout>
				</AuthProvider>
			</body>
		</html>
	);
}
