import type { Metadata } from "next";
import "./globals.css";
import { ConditionalLayout } from "@/components/ConditionalLayout";
import { Poppins } from "next/font/google";

const poppins = Poppins({
	subsets: ["latin"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
	title: "ATS by Team C",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${poppins.className} antialiased bg-slate-50`}>
				<ConditionalLayout>{children}</ConditionalLayout>
			</body>
		</html>
	);
}
