"""Added job_id and constraints

Revision ID: 20c7f582d798
Revises: a61156603aae
Create Date: 2026-03-23 12:39:14.469628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20c7f582d798'
down_revision = 'a61156603aae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.Integer(), nullable=False))
        batch_op.alter_column('admin_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint('unique_application', ['applicant_id', 'job_id'])
        batch_op.create_foreign_key(None, 'jobs', ['job_id'], ['job_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('unique_application', type_='unique')
        batch_op.alter_column('admin_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('job_id')

    # ### end Alembic commands ###
