"""link document to application

Revision ID: 58207578b18d
Revises: ee551e4d7087
Create Date: 2026-03-27 15:51:42.395747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58207578b18d'
down_revision = 'ee551e4d7087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.alter_column('comments',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=500),
               existing_nullable=True)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('documents_applicant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'application_reviews', ['review_id'], ['review_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('documents_applicant_id_fkey'), 'applicants', ['applicant_id'], ['applicant_id'])

    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.alter_column('comments',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
